### ISSUE TITLE
Fonts, too

### ISSUE THREAD

**Issue by PositiveUser** [BlankParticle/tailwind-plugin-realtime-colors#1]
How about setting fonts too?

**Comment by BlankParticle** [comment]
Having fonts is certainly a great idea, but there are some issues with getting fonts to work.
It was already in my roadmap.
but fonts are a whole different level of issue.

There are many ways to setup fonts.
- Using google fonts CDN
- Using `@fontsource`
- Any other font provider as user wishes

So I need to find a way to support all kind fonts with one config.
If you have any idea feel free to suggest that.

I will try to figure out fonts as soon as possible

**Comment by PositiveUser** [comment]
# Ideas about setting up fonts

## Realtime Colors URL:
```
https://www.realtimecolors.com/?colors=...&fonts=Archivo%20Narrow-Archivo
```

## Google Fonts CSS Import:
```css
@import url('https://fonts.googleapis.com/css?family=Archivo%20Narrow:700|Archivo:400');
```

## CSS Variables:
```css
--font-heading: "Archivo Narrow", theme(fontFamily.sans);
--font-body: 'Archivo', theme(fontFamily.sans);
```
## Tailwind JS/TS Config:
```js
{
  theme: {
    extend: {
      fontFamily: {
        heading: ['"Archivo Narrow"', ...defaultTheme.fontFamily.sans],
        body: ['"Archivo"', ...defaultTheme.fontFamily.sans],
      },
    }
  }
}
```
## Tailwind CSS (utilities):
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer utilities {
  .font-heading {
    font-family: "Archivo Narrow", theme(fontFamily.sans);
  }

  .font-body {
    font-family: "Archivo", theme(fontFamily.sans);
  }
}
```
